version: '3'

services:
  crdb:
    image: cockroachdb/cockroach:v22.1.10
    hostname: cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health?ready=1" ]
      interval: 3s
      timeout: 3s
      retries: 5
    command: start-single-node --insecure

  replicant:
    build:
      context: ./../replicant
      dockerfile: ./../replicant/replicant.Dockerfile
    restart:
      always
    ports:
      - "8000:8000"
    depends_on:
      crdb:
        condition: service_healthy

